# https://github.com/blakeblackshear/blakeshome-charts/tree/master/charts/frigate
# https://github.com/blakeblackshear/frigate
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: frigate
  namespace: kube-system
spec:
  repo: "https://blakeblackshear.github.io/blakeshome-charts/"
  chart: frigate
  version: 7.3.0
  targetNamespace: home-assistant
  valuesContent: |-
    image:
      tag: 0.13.2
    ingress:
      enabled: true
      hosts:
      - host: frigate.home.seanho.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: frigate-tls
        hosts:
        - frigate.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.org/websocket-services: frigate
    shmSize: 8Gi
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        size: 8Ti
        skipuninstall: true
    config: |
      detectors:
        cpu:
          type: cpu
          num_threads: 4
      mqtt:
        host: mqtt
        port: 1833
        user: frigate
        password: "{FRIGATE_MQTT_PASSWORD}"
      detect:
        width: 1280
        height: 720
        fps: 4
      record:
        enabled: true
        expire_interval: 120
        retain:
          days: 14
          mode: all
      events:
        max_seconds: 600
        pre_capture: 10
        post_capture: 10
        retain:
          default: 30
      ffmpeg:
          input_args: "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1"
      cameras:
        front_detect:
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@front.iot.seanho.com:554/Streaming/Channels/2
                roles:
                - rtmp
                - detect
        front_record:
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@front.iot.seanho.com:554/Streaming/Channels/1
                roles:
                - rtmp
                - record
