# https://github.com/blakeblackshear/blakeshome-charts/tree/master/charts/frigate
# https://github.com/blakeblackshear/frigate
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: frigate
  namespace: kube-system
spec:
  repo: "https://blakeblackshear.github.io/blakeshome-charts/"
  chart: frigate
  version: 7.6.0
  targetNamespace: home-assistant
  valuesContent: |-
    image:
      tag: 0.14.1
    ingress:
      enabled: true
      hosts:
      - host: frigate.home.seanho.com
        paths:
        - path: /
          portName: http
      tls:
      - secretName: frigate-tls
        hosts:
        - frigate.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.org/websocket-services: frigate
    shmSize: 8Gi
    tmpfs:
      sizeLimit: 8Gi
    persistence:
      config:
        enabled: true
        size: 8Gi
      media:
        enabled: true
        size: 8Ti
        storageClass: nvr
        skipuninstall: true
    envFromSecrets:
    - frigate-pw
    config: |
      mqtt:
        enabled: false
        host: mqtt
        user: "{FRIGATE_MQTT_USER}"
        password: "{FRIGATE_MQTT_PASSWORD}"
      detectors:
        cpu:
          type: cpu
          num_threads: 4
      detect:
        enabled: True
        fps: 4
      motion:
        enabled: True
      record:
        enabled: true
        expire_interval: 120
        retain:
          days: 14
          mode: all
      snapshots:
        enabled: True
      cameras:
        porch:
          audio:
            enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@porch.iot.seanho.com/cam/realmonitor?channel=1&subtype=0
                roles:
                - record
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@porch.iot.seanho.com/cam/realmonitor?channel=1&subtype=1
                roles:
                - detect
                - audio
        front:
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@front.iot.seanho.com/stream1
                roles:
                - record
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@front.iot.seanho.com/stream2
                roles:
                - detect
        rear:
          motion:
            mask:
            - "0.875,0,0.875,0.112,0.967,0.144,1,0.277,1,0"
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@rear.iot.seanho.com:554/Streaming/Channels/1
                roles:
                - record
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@rear.iot.seanho.com:554/Streaming/Channels/2
                roles:
                - detect
        cube2:
          motion:
            enabled: False
          detect:
            enabled: False
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@cube2.iot.seanho.com:554/Streaming/Channels/2
                roles:
                - detect
