# https://artifacthub.io/packages/helm/k8s-home-lab-repo/home-assistant
# https://hub.docker.com/r/homeassistant/home-assistant/tags
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: home-assistant
  namespace: kube-system
spec:
  repo: "https://k8s-home-lab.github.io/helm-charts/"
  chart: home-assistant
  version: 14.0.1
  targetNamespace: home-assistant
  valuesContent: |-
    image:
      tag: 2025.5.3
    ingress:
      main:
        enabled: true
        hosts:
        - host: ha.home.seanho.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: ha-tls
          hosts:
          - ha.home.seanho.com
        annotations:
          cert-manager.io/cluster-issuer: le-prod
          nginx.org/websocket-services: home-assistant
    persistence:
      config: 
        enabled: true
        retain: true
        existingClaim:
    postgresql:
      enabled: true
      persistence:
        enabled: true
      image:
        tag: 11.21.0
    prometheus:
      serviceMonitor:
        enabled: true
