# https://artifacthub.io/packages/helm/k8sonlab/zwave-js-ui
# https://github.com/zwave-js/zwave-js-ui
# /dev/serial/by-id/usb-0658_0200-if00
# Edit yaml manually:
# volumeMounts:
# - mountPath: /dev/zwave
#   name: zwave
# volumes:
# - hostPath:
#     path: /dev/serial/by-id/usb-0658_0200-if00
#     type: ""
#   name: zwave
#
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: zwave
  namespace: kube-system
spec:
  repo: "https://charts.ar80.eu"
  chart: zwave-js-ui
  version: 0.2.140
  targetNamespace: home-assistant
  valuesContent: |-
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      tag: 10.5.1
    securityContext:
      privileged: true
    envFrom:
    - secretRef:
        name: zwave
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      existingClaim: zwave-config
    ingress:
      enabled: true
      hosts:
      - host: zwave.home.seanho.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: zwave-tls
        hosts:
        - zwave.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.org/websocket-services: zwave
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "feature.node.kubernetes.io/usb-0658_0200.present"
              operator: Exists
