apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: loki
  objectStoreNamespace: rook-ceph
