---
apiVersion: v1
kind: Service
metadata:
  name: docker
  namespace: registry
spec:
  selector:
    app: registry
  type: ClusterIP
  ports:
  - name: docker
    protocol: TCP
    port: 5000
    targetPort: 5000
