apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: "https://charts.jetstack.io"
  chart: cert-manager
  version: 0.15.1
  targetNamespace: cert-manager

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: le-staging
spec:
  acme:
    email: letsencrypt@seanho.com
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: le-staging-key
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@seanho.com
            apiTokenSecretRef:
              name: cf-api-token
              key: api-token
