apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: jetstack/cert-manager
  repo: "https://charts.jetstack.io"
  version: 0.12
  valuesContent: |-
    webhook.enabled: false

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: le-staging
spec:
  acme:
    email: letsencrypt@seanho.com
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: le-staging-key
    solvers:
      - http01:
          ingress:
            class: traefik
