apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://charts.k8s.land"
  chart: k8s-land/gitea
  version: 1.2.1
  targetNamespace: default
  valuesContent: |-
    ingress:
      hostname: gitea.home.seanho.com
      certManager: false
      tls:
    service:
      http:
        externalHost: gitea.home.seanho.com
      ssh:
        serviceType: LoadBalancer
        port: 26
        externalHost: gitea.home.seanho.com
    persistence:
      enabled: true
      annotations:
        "helm.sh/resource-policy": keep
