apiVersion: v1
kind: Namespace
metadata:
  name: gitea

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://charts.k8s.land"
  chart: gitea
  version: 1.3.3
  targetNamespace: gitea
  valuesContent: |-
    images:
      gitea: gitea/gitea:1.12
    ingress:
      enabled: false
    service:
      http:
        serviceType: LoadBalancer
        port: 80
        externalHost: gitea.home.seanho.com
      ssh:
        serviceType: LoadBalancer
        port: 26
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      annotations:
        "helm.sh/resource-policy": keep
    mariadb:
      master:
        persistence:
          enabled: true

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-gitea-ssh
  namespace: gitea
  labels:
    app: gitea-gitea
  annotations:
    metallb.universe.tf/allow-shared-ip: gitea
spec:
  loadBalancerIP: 10.90.4.98

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-gitea-http
  namespace: gitea
  labels:
    app: gitea-gitea
  annotations:
    metallb.universe.tf/allow-shared-ip: gitea
spec:
  loadBalancerIP: 10.90.4.98

