# https://gitea.com/gitea/helm-chart/releases
# https://hub.docker.com/r/gitea/gitea/tags?page=1&ordering=last_updated
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://dl.gitea.io/charts/"
  chart: gitea
  version: 8.3.0
  targetNamespace: gitea
  valuesContent: |-
    image:
      tag: 1.19.4
    persistence:
      size: 20Gi
    gitea:
      admin:
        existingSecret: gitea-admin
      config:
        APP_NAME: "Anchorlytics Code"
        server:
          PPROF_ENABLED: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    ingress:
      enabled: true
      hosts:
      - host: code.anchorlytics.com
        paths:
        - path: /
          pathType: Prefix
      - host: code.home.seanho.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: gitea-tls
        hosts:
        - code.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
    postgresql:
      auth:
        secretKeys:
          adminPasswordKey: password
          userPasswordKey: postgres-password
    extraVolumes:
    - name: import
      nfs:
        server: nfs.home.seanho.com
        path: /srv/share/git
        readOnly: true
    extraContainerVolumeMounts:
    - name: import
      mountPath: /mnt/import
