# https://gitea.com/gitea/helm-chart/releases
# https://codeberg.org/forgejo/-/packages/container/forgejo/versions
# GIT_GC_REPOS workaround: https://gitea.com/gitea/helm-chart/issues/488
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://dl.gitea.io/charts/"
  chart: gitea
  version: 9.5.1
  targetNamespace: gitea
  valuesContent: |-
    replicaCount: 2
    image:
      #      registry: codeberg.org
      #      repository: forgejo/forgejo
      tag: 1.20.5
    persistence:
      size: 20Gi
      storageClass: shared-ssd
      accessModes: 
      - ReadWriteMany
    gitea:
      admin:
        existingSecret: gitea-admin
      config:
        APP_NAME: "Anchorlytics Code"
        server:
          PPROF_ENABLED: true
        "cron.GIT_GC_REPOS": 
          ENABLED: false
        actions:
          ENABLED: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    ingress:
      enabled: true
      hosts:
      - host: code.home.seanho.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: gitea-tls
        hosts:
        - code.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
#    extraVolumes:
#    extraContainerVolumeMounts:
