apiVersion: v1
kind: Namespace
metadata:
  name: gitea

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://charts.k8s.land"
  chart: gitea
  version: 1.3.3
  targetNamespace: gitea
  valuesContent: |-
    ingress:
      hostname: gitea.home.seanho.com
      tls:
        - hosts:
          - gitea.home.seanho.com
          secretName: home-seanho-tls
    service:
      ssh:
        serviceType: LoadBalancer
        port: 26
        externalHost: gitea.home.seanho.com
        externalIPs:
          - 10.90.4.98
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      annotations:
        "helm.sh/resource-policy": keep
