# https://github.com/k8s-at-home/charts/blob/master/charts/stable/home-assistant/Chart.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: home-assistant
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: home-assistant
  version: 11.0.3
  targetNamespace: home-assistant
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
        - host: ha.home.seanho.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: ha-tls
          hosts:
          - ha.home.seanho.com
        annotations:
          cert-manager.io/cluster-issuer: le-prod
          nginx.org/websocket-services: home-assistant
    persistence:
      config:
        enabled: true
      usb: 
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0
    postgresql:
      enabled: true
      persistence:
        enabled: true
    prometheus:
      serviceMonitor:
        enabled: true
    securityContext:
      privileged: true
    nodeSelector:
      zwave: usb
