# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: "https://kubernetes.github.io/ingress-nginx"
  chart: ingress-nginx
  version: 4.0.13
  targetNamespace: ingress-nginx
  valuesContent: |-
    service:
      loadBalancerIP: 10.90.4.96
    controller:
      watchIngressWithoutClass: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
