
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: "https://kubernetes.github.io/ingress-nginx"
  chart: ingress-nginx
  version: 3.29.0
  targetNamespace: ingress-nginx
  valuesContent: |-
    service:
      loadBalancerIP: 10.90.4.96
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false
