
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  repo: "https://kubernetes.github.io/dashboard"
  chart: kubernetes-dashboard
  version: 4.0.3
  targetNamespace: kubernetes-dashboard
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
      - k8s.home.seanho.com
      tls:
      - secretName: k8s-dash-tls
        hosts:
        - k8s.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
    nodeSelector:
      kubernetes.io/hostname: wreck
    metricsScraper:
      enabled: false
    metrics-server:
      enabled: false

