apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  repo: "https://charts.bitnami.com/bitnami"
  chart: metallb
  version: 0.1.27
  valuesContent: |-
    configInline:
      address-pools:
        - name: MGMT
          protocol: layer2
          addresses:
            - 10.90.3.96/27
        - name: LAN
          protocol: layer2
          addresses:
            - 10.90.4.96/27
        - name: IOT
          protocol: layer2
          addresses:
            - 10.90.8.96/27
