# https://github.com/bitnami/charts/blob/master/bitnami/metallb/
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  repo: "https://charts.bitnami.com/bitnami"
  chart: metallb
  version: 3.0.1
  valuesContent: |-
    configInline:
      address-pools:
        - name: MGMT
          protocol: layer2
          addresses:
            - 10.90.3.96/27
        - name: LAN
          protocol: layer2
          addresses:
            - 10.90.4.96/27
        - name: IOT
          protocol: layer2
          addresses:
            - 10.90.8.96/27
    prometheusRule:
      enabled: true
    controller:
      nodeSelector:
        role: ingress
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    speaker:
      nodeSelector:
        role: ingress
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
