---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: kube-system
spec:
  repo: "https://nextcloud.github.io/helm/"
  chart: nextcloud
  version: 2.6.5
  targetNamespace: nextcloud
  valuesContent: |-
    nextcloud:
      host: cloud.home.seanho.com
      persistence:
        subPath: 
    ingress:
      enabled: true
      hosts:
      - cloud.home.seanho.com
      tls:
      - secretName: nextcloud-tls
        hosts:
        - cloud.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
    persistence:
      enabled: true
    nginx:
      enabled: true
    redis:
      enabled: true
    cronjob:
      enabled: true
    hpa:
      enabled: false
    metrics:
      enabled: false

# cm/photo: BUCKET_HOST, BUCKET_NAME, BUCKET_PORT
# secret/photo: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
