# https://github.com/kubernetes-sigs/node-feature-discovery/tree/gh-pages/charts
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  repo: "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chart: node-feature-discovery
  version: 0.12.0
  targetNamespace: node-feature-discovery
  valuesContent: |-
    worker:
      config:
        core:
          sleepInterval: 5m
        sources:
          usb:
            deviceClassWhiteList: ["02", "03"]
            deviceLabelFields: [vendor, device]
