apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  version: 1.85.0
  targetNamespace: kube-system
  valuesContent: |-
    rbac.enabled: true
    ssl.enabled: false
    metrics.prometheus.enabled: false
    kubernetes:
      ingressEndpoint:
        hostname: traefik
        useDefaultPublishedService: true
    serviceType: NodePort
    dashboard:
      enabled: true
      domain: traefik.home.seanho.com
      serviceType: NodePort
    deployment:
      hostPort:
        httpEnabled: true
        httpsEnabled: true
        dashboardEnabled: true
