---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: unifi
  version: 1.0.0
  targetNamespace: unifi
  valuesContent: |-
    image:
      tag: 5.6
    timezone: America/Vancouver
    ingress:
      enabled: true
      hosts:
        - unifi.home.seanho.com
      tls:
        - secretName: unifi-tls
          hosts:
            - unifi.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
    customCert:
      enabled: true
      isChain: true
      certSecret: unifi-tls
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
