apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: stable/unifi
  version: 0.5.2
  targetNamespace: default
  valuesContent: |-
    image:
      tag: 5.6
    guiService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      port: 443
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    timezone: America/Vancouver
