# delete: helmchart deploy po svc pvc cm secret
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: stable/unifi
  version: 0.7.0
  targetNamespace: unifi
  valuesContent: |-
    image:
      tag: 5.6
    timezone: America/Vancouver
    guiService:
      type: LoadBalancer
      port: 443
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
