# delete: helmchart deploy po svc pvc cm secret
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: stable/unifi
  version: 0.8.1
  targetNamespace: unifi
  valuesContent: |-
    image:
      tag: 5.6
    timezone: America/Vancouver
    unifiedService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
