apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: stable/unifi
  version: 0.5.2
  targetNamespace: default
  valuesContent: |-
    image:
      tag: 5.6
    unifiedService:
      enabled: true
      type: LoadBalancer
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - unifi.home.seanho.com
    timezone: America/Vancouver
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
