apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: stable/unifi
  version: 0.5.2
  targetNamespace: default
  valuesContent: |-
    image:
      tag: 5.6
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.90.4.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - unifi.home.seanho.com
    timezone: America/Vancouver
