---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: kube-system
spec:
  repo: "https://charts.rook.io/release"
  chart: rook-ceph
  targetNamespace: rook-ceph
  pspEnable: false
  valuesContent: |-
    currentNamespaceOnly: true
    nodeSelector:
      ceph: yes
    discover:
      nodeAffinity: "ceph-osd=yes"
