---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: kube-system
spec:
  repo: "https://charts.rook.io/release"
  chart: rook-ceph
  targetNamespace: rook-ceph
  valuesContent: |-
    currentNamespaceOnly: true
    nodeSelector:
      ceph: true
    discover:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-osd
              operator: Exists
