apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.5
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dataDirHostPath: /var/lib/rook
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-osd
              operator: Exists
  driveGroups:
  - name: spanish-hdd
    spec:
      encrypted: true
      data_devices:
        rotational: 1
      db_devices:
        rotational: 0
        size: '1T:'
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - spanish
  - name: spanish-nvme
    spec:
      encrypted: true
      data_devices:
        rotational: 0
        size: '1T:'
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - spanish
  - name: jericho-hdd
    spec:
      encrypted: true
      data_devices:
        rotational: 1
      db_devices:
        model: 'ADATA SX8200NP'
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - jericho
  - name: jericho-nvme
    spec:
      encrypted: true
      data_devices:
        model: 'SAMSUNG MZFLV512HCJH-000MV'
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - jericho
