apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.5
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
  dataDirHostPath: /var/lib/rook
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-role
              operator: In
              values:
              - osd
  driveGroups:
  - name: hdd
    spec:
      encrypted: true
      data_devices:
        rotational: 1
      db_devices:
        rotational: 0
        size: '400G:500G'
  - name: nvme
    spec:
      encrypted: true
      data_devices:
        rotational: 0
        size: '900G:'
