apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: shared
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
    deviceClass: nvme
  dataPools:
    - failureDomain: host
      replicated:
        size: 2
      deviceClass: nvme
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

