apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.13
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: false
  mon:
    count: 3
    allowMultiplePerNode: false
  crashCollector:
    disable: true
  dataDirHostPath: /var/lib/rook
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-role
              operator: In
              values:
              - osd
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      encryptedDevice: "true"
#    nodes:
#    - name: 
#      devices:
#      - name:
#        config:
#          metadataDevice:
