apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.9
  dashboard:
    enabled: true
    type: LoadBalancer
  monitoring:
    enabled: true
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  driveGroups:
  - name: spanish-hdd
    spec:
      encrypted: true
      data_devices:
        rotational: 1
      db_devices:
        vendor: SanDisk
      db_slots: 6
    placement:
      nodeAffinity:
        nodeSelector:
          kubernetes.io/hostname: spanish
  - name: spanish-nvme
    spec:
      encrypted: true
      data_devices:
        vendor: SanDisk
    placement:
      nodeAffinity:
        nodeSelector:
          kubernetes.io/hostname: spanish
