# https://quay.io/repository/ceph/ceph?tab=tags
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.1
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
  mgr:
    count: 3
  mon:
    count: 3
    allowMultiplePerNode: false
  crashCollector:
    disable: true
  dataDirHostPath: /var/lib/rook
  resources:
    osd:
      requests:
        memory: 2G
      limits:
        memory: 8G
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-role
              operator: In
              values:
                - osd
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      encryptedDevice: "true"
