apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  cephVersion:
    image: ceph/ceph:v15.2.13
  mgr:
    count: 2
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: false
  crashCollector:
    disable: true
  dataDirHostPath: /var/lib/rook
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-role
              operator: In
              values:
              - osd
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      encryptedDevice: "true"
#    nodes:
#    - name: 
#      devices:
#      - name:
#        config:
#          metadataDevice:
