# https://quay.io/repository/ceph/ceph?tab=tags
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.3
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
  mgr:
    count: 2
  mon:
    count: 3
    allowMultiplePerNode: false
  crashCollector:
    disable: true
  dataDirHostPath: /var/lib/rook
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-role
              operator: In
              values:
                - osd
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      encryptedDevice: "true"
