apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.4
  dashboard:
    enabled: true
    type: LoadBalancer
  monitoring:
    enabled: true
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  driveGroups:
  - name: spanish-hdd
    spec:
      encrypted: true
      data_devices:
        rotational: 1
      db_devices:
        rotational: 0
        size: '1TB:'
    placement:
      nodeAffinity:
        nodeSelector:
          kubernetes.io/hostname: spanish
  - name: spanish-nvme
    spec:
      encrypted: true
      data_devices:
        rotational: 0
        size: '1TB:'
    placement:
      nodeAffinity:
        nodeSelector:
          kubernetes.io/hostname: spanish
  - name: jericho-hdd
    spec:
      encrypted: true
      data_devices:
        rotational: 1
      db_devices:
        rotational: 0
        model: 'SX8200'
    placement:
      nodeAffinity:
        nodeSelector:
          kubernetes.io/hostname: jericho
  - name: jericho-nvme
    spec:
      encrypted: true
      data_devices:
        rotational: 0
        model: 'PM951'
    placement:
      nodeAffinity:
        nodeSelector:
          kubernetes.io/hostname: jericho
