# https://github.com/rook/rook/releases
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: kube-system
spec:
  repo: "https://charts.rook.io/release"
  chart: rook-ceph
  version: v1.12.7
  targetNamespace: rook-ceph
  valuesContent: |-
    image:
      tag: v1.12.7
    currentNamespaceOnly: true
    nodeSelector:
      role: ceph
    discover:
      nodeAffinity: ceph-role=osd
    enableDiscoveryDaemon: true
    monitoring:
      enabled: true
    csi:
      nfs:
        enabled: true
