---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: kube-system
spec:
  repo: "https://charts.rook.io/release"
  chart: rook-ceph
  version: 1.6.7
  targetNamespace: rook-ceph
  pspEnable: false
  valuesContent: |-
    image:
      tag: v1.6.7
    currentNamespaceOnly: true
    nodeSelector:
      role: ceph
