# For manual interaction with helm
---
apiVersion: v1
kind: Pod
metadata:
  name: klipper-helm
  namespace: kube-system
spec:
  containers:
  - name: k8s
    image: rancher/klipper-helm:v0.4.3
    command: ["/bin/sleep"]
    args: ["600"]
  serviceAccount: helm-home-assistant
  serviceAccountName: helm-home-assistant

