# https://github.com/bitnami/charts/tree/master/bitnami/mariadb
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mariadb
  namespace: kube-system
spec:
  repo: "https://charts.bitnami.com/bitnami"
  chart: mariadb
  version: 11.2.1
  targetNamespace: photoprism
  valuesContent: |-
    auth:
      database: photoprism
      username: photoprism
      existingSecret: pw
    metrics:
      enabled: true
