
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  repo: "https://kubernetes.github.io/dashboard"
  chart: kubernetes-dashboard
  version: 4.0.2
  targetNamespace: kubernetes-dashboard
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
      - k8s.mgmt.seanho.com
      tls:
    nodeSelector:
      kubernetes.io/hostname: wreck
    metricsScraper:
      enabled: false
    metrics-server:
      enabled: false

