apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  repo: "https://charts.bitnami.com/bitnami"
  chart: metallb
  version: 2.3.2
  valuesContent: |-
    configInline:
      address-pools:
        - name: MGMT
          protocol: layer2
          addresses:
            - 10.90.3.96/27
        - name: LAN
          protocol: layer2
          addresses:
            - 10.90.4.96/27
        - name: IOT
          protocol: layer2
          addresses:
            - 10.90.8.96/27
    prometheusRule:
      enabled: true
    controller:
      prometheus:
        serviceMonitor:
          enabled: true
    speaker:
      prometheus:
        serviceMonitor:
          enabled: true
