---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://dl.gitea.io/charts/"
  chart: gitea
  version: 2.1.11
  targetNamespace: gitea
  valuesContent: |-
    gitea:
      config:
        APP_NAME: "Anchorlytics Code"
      cache:
        builtIn:
          enabled: true
    persistence:
      enabled: true
      size: 20Gi
    postgresql:
      persistence:
        enabled: true
    ingress:
      enabled: true
      hosts:
      - git.home.seanho.com
      tls:
      - secretName: gitea-tls
        hosts:
        - git.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
    metrics:
      enabled: false
