# Override to add dnsConfig to containers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: gitea
  name: gitea
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitea
      app.kubernetes.io/name: gitea
  serviceName: gitea
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: gitea
        app.kubernetes.io/name: gitea
    spec:
      containers:
      - env:
        - name: SSH_LISTEN_PORT
          value: "22"
        - name: SSH_PORT
          value: "22"
        image: gitea/gitea:1.13.2
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        name: gitea
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      initContainers:
      - command:
        - /usr/sbin/init_gitea.sh
        image: gitea/gitea:1.13.2
        name: init
        volumeMounts:
        - mountPath: /usr/sbin
          name: init
        - mountPath: /etc/gitea/conf
          name: config
        - mountPath: /data
          name: data
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - name: init
        secret:
          defaultMode: 511
          secretName: gitea-init
      - name: config
        secret:
          defaultMode: 420
          secretName: gitea
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
