---
apiVersion: v1
kind: Service
metadata:
  name: gitea-gitea-ssh
  namespace: gitea
  labels:
    app: gitea-gitea
  annotations:
    metallb.universe.tf/allow-shared-ip: gitea
spec:
  loadBalancerIP: 10.90.4.98

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-gitea-http
  namespace: gitea
  labels:
    app: gitea-gitea
  annotations:
    metallb.universe.tf/allow-shared-ip: gitea
spec:
  loadBalancerIP: 10.90.4.98

