apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: shared
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
    deviceClass: ssd
  dataPools:
  - name: ssd
    replicated:
      size: 3
    deviceClass: ssd
  - name: hdd
    erasureCoded:
      dataChunks: 3
      codingChunks: 2
    deviceClass: hdd
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

