---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-nfs-lb
  namespace: rook-ceph
spec:
  type: LoadBalancer
  ports:
    - name: nfs
      port: 2049
  externalTrafficPolicy: Local
  selector:
    app: rook-ceph-nfs
    ceph_nfs: cephnfs
    instance: a
