# https://github.com/rook/rook/blob/master/deploy/examples/nfs-load-balancer.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-nfs-lb
  namespace: rook-ceph
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.90.4.99
spec:
  type: LoadBalancer
  ports:
    - name: nfs
      port: 2049
  selector:
    app: rook-ceph-nfs
    ceph_nfs: cephnfs
    instance: a
