apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: pods
  namespace: rook-ceph
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  failureDomain: host
  replicated:
    size: 2
  parameters:
    min_size: "1"
    compression_mode: passive
  deviceClass: ssd

