---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copy-shared
  namespace: nextcloud
  labels:
    app: copy-shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copy-shared
  template:
    metadata:
      labels:
        app: copy-shared
    spec:
      containers:
      - name: debian
        image: debian:stable-slim
        command:
        - sleep
        args:
        - infinity
        volumeMounts:
        - name: shared
          mountPath: /mnt/shared
        - name: photos
          mountPath: /mnt/photos
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared
      - name: photos
        persistentVolumeClaim:
          claimName: photos
          readOnly: false

