# https://github.com/nextcloud/helm/releases
# https://hub.docker.com/r/library/nextcloud/tags/
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: kube-system
spec:
  repo: "https://nextcloud.github.io/helm/"
  chart: nextcloud
  version: 4.2.1
  targetNamespace: nextcloud
  valuesContent: |-
    image:
      tag: 27.0.2-fpm-alpine
    replicaCount: 2
    ingress:
      enabled: true
      className: external
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        kubernetes.io/ingress.class: external
      tls:
      - secretName: nextcloud-tls
        hosts:
        - cloud-int.seanho.com
    nextcloud:
      host: cloud-int.seanho.com
      existingSecret:
        enabled: true
        secretName: nextcloud-pw
        usernameKey: user
        passwordKey: password
        smtpUsernameKey: smtp-user
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      mail:
        enabled: true
        fromAddress: nextcloud@seanho.com
        domain: seanho.com
        smtp:
          secure: true
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array(
           'trusted_proxies' => array('10.42.0.0/16'),
           'overwrite_protocol' => 'https'
          );
        custom.config.php: |-
          <?php
          $CONFIG = array(
           'default_phone_region' => 'US'
          );
      extraVolumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos
          readOnly: false
      - name: import
        nfs:
          server: nfs.home.seanho.com
          path: /srv/photo
          readOnly: true
      extraVolumeMounts:
      - name: photos
        mountPath: /mnt/photos
      - name: import
        mountPath: /mnt/import
    persistence:
      enabled: true
      storageClass: shared-ssd
      accessMode: ReadWriteMany
      size: 10G
      nextcloudData:
        enabled: true
        storageClass: shared-ssd
        accessMode: ReadWriteMany
        size: 400G
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: user
        passwordKey: password
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: nextcloud-db
            secretKeys:
              userPasswordKey: password
              adminPasswordKey: postgres-password
              replicationPasswordKey: replication-password
      primary:
        persistence:
          enabled: true
    redis:
      enabled: true
      auth:
        existingSecret: nextcloud-pw
        existingSecretPasswordKey: redis-password
    cronjob:
      enabled: true
    metrics:
      enabled: false

