# https://github.com/nextcloud/helm/releases
# https://hub.docker.com/r/library/nextcloud/tags/
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: kube-system
spec:
  repo: "https://nextcloud.github.io/helm/"
  chart: nextcloud
  version: 3.5.7
  targetNamespace: nextcloud
  valuesContent: |-
    image:
      tag: 26.0.0-fpm-alpine
    ingress:
      enabled: true
      tls:
      - secretName: nextcloud-tls
        hosts:
        - cloud.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
    nextcloud:
      host: cloud.home.seanho.com
      existingSecret:
        enabled: true
        secretName: nextcloud-pw
        usernameKey: user
        passwordKey: password
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array(
           'trusted_proxies' => array('10.42.0.0/16'),
           'overwrite_protocol' => 'https'
          );
      extraVolumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos
          readOnly: true
            #      - name: import
            #        nfs:
            #          server: nfs.home.seanho.com
            #          path: /srv/photo
      extraVolumeMounts:
      - name: photos
        mountPath: /mnt/photos
          #      - name: import
          #        mountPath: /mnt/import
    persistence:
      enabled: true
      size: 10G
      nextcloudData:
        enabled: true
        size: 400G
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: user
        passwordKey: password
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: nextcloud-db
            secretKeys:
              userPasswordKey: password
              adminPasswordKey: postgres-password
              replicationPasswordKey: replication-password
      primary:
        persistence:
          enabled: true
    redis:
      enabled: true
      auth:
        existingSecret: nextcloud-pw
        existingSecretPasswordKey: redis-password
    cronjob:
      enabled: true
    metrics:
      enabled: false

