# https://github.com/nextcloud/helm/releases
# https://hub.docker.com/r/library/nextcloud/tags/
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: kube-system
spec:
  repo: "https://nextcloud.github.io/helm/"
  chart: nextcloud
  version: 6.2.4
  targetNamespace: nextcloud
  valuesContent: |-
    image:
      tag: 30.0.2-fpm-alpine
    replicaCount: 2
    ingress:
      enabled: true
      className: external
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        kubernetes.io/ingress.class: external
        nginx.ingress.kubernetes.io/proxy-body-size: 1g
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      tls:
      - secretName: nextcloud-tls
        hosts:
        - cloud.seanho.com
    nextcloud:
      host: cloud.seanho.com
      existingSecret:
        enabled: true
        secretName: nextcloud-pw
        usernameKey: user
        passwordKey: password
        smtpUsernameKey: smtp-user
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      mail:
        enabled: true
        fromAddress: nextcloud@seanho.com
        domain: seanho.com
        smtp:
          secure: true
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array(
           'trusted_proxies' => ['127.0.0.1/8', '10.42.0.0/16'],
           'overwrite_protocol' => 'https',
           'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
           'maintenance_window_start' => 3,
          );
        custom.config.php: |-
          <?php
          $CONFIG = array(
           'default_phone_region' => 'US'
          );
      extraVolumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos
          readOnly: false
      - name: videos
        persistentVolumeClaim:
          claimName: videos
          readOnly: false
      - name: shared
        persistentVolumeClaim:
          claimName: shared
          readOnly: false
      extraVolumeMounts:
      - name: photos
        mountPath: /mnt/photos
      - name: videos
        mountPath: /mnt/videos
      - name: shared
        mountPath: /mnt/shared
    persistence:
      enabled: true
      storageClass: shared-ssd
      accessMode: ReadWriteMany
      size: 10G
      nextcloudData:
        enabled: true
        storageClass: shared-ssd
        accessMode: ReadWriteMany
        size: 800G
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: user
        passwordKey: password
    postgresql:
      enabled: true
      image:
        tag: 15.7.0
      global:
        postgresql:
          auth:
            existingSecret: nextcloud-db
            secretKeys:
              userPasswordKey: password
              adminPasswordKey: postgres-password
              replicationPasswordKey: replication-password
      primary:
        resourcesPreset: micro
        persistence:
          enabled: true
    redis:
      enabled: true
      auth:
        existingSecret: nextcloud-pw
        existingSecretPasswordKey: redis-password
    cronjob:
      enabled: true
    metrics:
      enabled: true

