---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos
  namespace: nextcloud
spec:
  storageClassName: shared-hdd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2T
