apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: big
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
    parameters:
      min_size: "1"
    deviceClass: ssd
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    deviceClass: hdd
  gateway:
    type: s3
    port: 80
    instances: 2
