apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: shared
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
    deviceClass: ssd
  dataPools:
  - failureDomain: host
    replicated:
      size: 2
    deviceClass: ssd
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

