apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: shared
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
    deviceClass: ssd
  dataPools:
  - failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    deviceClass: hdd
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 3
    activeStandby: true

