# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-external
  namespace: kube-system
spec:
  repo: "https://kubernetes.github.io/ingress-nginx"
  chart: ingress-nginx
  version: 4.7.1
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      name: external
      kind: DaemonSet
      nodeSelector:
        role: ingress
      ingressClassResource:
        name: external
        controllerValue: "k8s.io/ingress-external"
      service:
        loadBalancerIP: 10.90.4.98
      config:
        use-proxy-protocol: true
        enable-real-ip: true
        proxy-real-ip-cidr: 10.90.10.67/24
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
