apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: nvr-data
  namespace: rook-ceph
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  failureDomain: host
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
  deviceClass: hdd

