---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mgmt
  namespace: metallb-system
spec:
  ipAddressPools:
  - mgmt
  nodeSelectors:
  - matchLabels:
      role: ingress
