
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: unifi
  version: 1.3.1
  targetNamespace: unifi
  valuesContent: |-
    image:
      tag: 5.6
    timezone: America/Vancouver
    ingress:
      enabled: true
      hosts:
      - unifi.home.seanho.com
      tls:
      - hosts:
        - unifi.home.seanho.com
        secretName: unifi-tls
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi

