
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: unifi
  version: 4.6.1
  targetNamespace: unifi
  valuesContent: |-
    image:
      tag: v5.14.23
    timezone: America/Vancouver
    persistence:
      enabled: true
      existingClaim: unifi
    ingress:
      enabled: true
      hosts:
      - unifi.home.seanho.com
      tls:
      - hosts:
        - unifi.home.seanho.com
        secretName: unifi-tls
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.90.3.97
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi

