# https://github.com/k8s-at-home/charts/tree/master/charts/stable/unifi
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: unifi
  version: 4.6.1
  targetNamespace: unifi
  valuesContent: |-
    image:
      tag: v5.14.23
    env:
      TZ: America/Vancouver
    persistence:
      data:
        enabled: true
        existingClaim: unifi
    service:
      main:
        ports:
          controller:
            enabled: false
          stun:
            enabled: false
          syslog:
            enabled: false
          discovery:
            enabled: false
          speedtest:
            enabled: false
      tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.90.3.97
        annotations:
          metallb.universe.tf/allow-shared-ip: unifi
        ports:
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          speedtest:
            enabled: true
            port: 3478
            protocol: TCP
      udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.90.3.97
        annotations:
          metallb.universe.tf/allow-shared-ip: unifi
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      main:
        enabled: true
        hosts:
        - host: unifi.home.seanho.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - unifi.home.seanho.com
          secretName: unifi-tls
        annotations:
          cert-manager.io/cluster-issuer: le-prod
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

