---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nut-client
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: network-ups-tools
  version: 6.2.0
  targetNamespace: nut
  valuesContent: |-
    config:
      files:
        nut.conf: |
          MODE=netclient
        upsmon.conf: |
          MONITOR apc@nut-network-ups-tools 1 secondary secondary_pass secondary
          POLLFREQ 15
          DEADTIME 60
          SHUTDOWNCMD "/sbin/shutdown -h now"
    securityContext:
      privileged: true
    nodeSelector:
      ups: apc
