
# https://github.com/k8s-at-home/charts/tree/master/charts/stable/network-ups-tools
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nut
  namespace: kube-system
spec:
  repo: "https://k8s-at-home.com/charts"
  chart: network-ups-tools
  version: 6.2.0
  targetNamespace: nut
  valuesContent: |-
    config:
      files:
        ups.conf: |
          [apc]
          driver=usbhid-ups
          port=auto
          vendorid=051d
          productid=0002
          sdorder=0
          [cp]
          driver=usbhid-ups
          port=auto
          vendorid=0764
          productid=0501
          sdorder=1
        upsd.users: |
          [admin]
          password = admin_pass
          actions = set
          actions = fsd
          instcmds = all
          [primary]
          password = primary_pass
          upsmon primary
          [secondary]
          password = secondary_pass
          upsmon secondary
        upsmon.conf: |
          MONITOR apc 0 primary primary_pass primary
          MONITOR cp 1 primary primary_pass primary
          POLLFREQ 15
          DEADTIME 60
          SHUTDOWNCMD "/sbin/shutdown -h now"
    securityContext:
      privileged: true
    service:
      main:
        ports:
          http:
            enabled: true
    ingress:
      main:
        enabled: true
        hosts:
        - host: ups.home.seanho.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: nut-tls
          hosts:
          - ups.home.seanho.com
        annotations:
          cert-manager.io/cluster-issuer: le-prod
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    nodeSelector:
      "feature.node.kubernetes.io/usb-0764_0501.present": "true"
