---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: "https://charts.jetstack.io"
  chart: cert-manager
  version: 1.0.3
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
    ingressShim:
      defaultIssuerName: le-prod
      defaultIssuerKind: ClusterIssuer
    extraArgs:
      - "--dns01-recursive-nameservers-only"
      - "--dns01-recursive-nameservers=1.1.1.1:53"
