# https://artifacthub.io/packages/helm/cert-manager/cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: "https://charts.jetstack.io"
  chart: cert-manager
  version: 1.13.1
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
    ingressShim:
      defaultIssuerName: le-prod
      defaultIssuerKind: ClusterIssuer
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "1.1.1.1:53"
