# https://hub.docker.com/r/shinobisystems/shinobi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinobi
  namespace: shinobi
  annotations:
    deployDate: "2022-12-23"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinobi
  template:
    metadata:
      labels:
        app: shinobi
    spec:
      containers:
      - name: shinobi
        image: "shinobisystems/shinobi:latest"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: autoload
          mountPath: /home/Shinobi/libs/customAutoLoad
        - name: db
          mountPath: /var/lib/mysql
        - name: videos
          mountPath: /home/Shinobi/videos
        - name: plugins
          mountPath: /home/Shinobi/plugins
        - name: streams
          mountPath: /dev/shm/streams
        resources:
          requests:
            cpu: 8
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: autoload
        persistentVolumeClaim:
          claimName: autoload
      - name: db
        persistentVolumeClaim:
          claimName: db
      - name: videos
        persistentVolumeClaim:
          claimName: videos
      - name: plugins
        persistentVolumeClaim:
          claimName: plugins
      - name: streams
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
