---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: shinobi
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
