---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: shinobi
data:
  conf.json: >-
    {
      "pluginkeys": {}
    }
  super.json: >-
    [{
      "mail": "shinobi@seanho.com",
      "pass": "samplepassword"
    }]
