---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos
  namespace: shinobi
spec:
  storageClassName: ceph-bulk
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4T
