---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos
spec:
  storageClassName: ceph-big
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4TB
